feat: filtering map
toppingskorea/toppings-client pull request #35
Opened 2022-12-15 12:59 UTC by po4tion

# Describe your changes

- map page(restaurant search, eating habit search, nationaliy serach)
- histories
- card list

## Issue ticket number and link (optional)

- #26 

## Checklist

- [X] 🤔 이 프로젝트의 스타일 가이드를 따르나요?
- [X] 🤔 머지하기 전에 스스로 코드에 문제가 없음을 확인했나요?
- [X] 🤔 필요한 주석을 필요한 곳에 넣어주었나요?
- [X] ⛔️ (필수) base 브랜치를 pull 받았나요?!

## Next Step Todo (optional)

## Questions

- 💬 질문 사항이에요!
- 🤷‍♂️ 확인 받고 싶은 부분이에요!
- 🔥 이건 꼭 확인해주세요!

bottom listitems width flex 1로 처리

view list, view maps 기능 추가해야함.

카카오 맵 이벤트 무한 페칭 이슈 해결해야함. tilesloaded 라는 맵 이벤트를 사용하게 되면 해당 이벤트가 계속 작동됨

컴포넌트 최적화 작업 해야함. (모달 확장성 버튼 1개인 애도 있음)

검색 엔터 기능 추가.(현재 마우스 클릭 기능만 작동)

그 외에 추가적인 사항들 있으면 적어주셈. 프로세스가 이상하다던지.

2022-12-15 16:01 UTC, ChanhyukPark-Tech requested changes
Map 과관련된 코어로직은 아직 테스트하기에 PR이 불완전하여 리뷰남기지않았습니다!
리뷰남긴거 수정해주시면 map과 관련된 리뷰 남기도록 하겠습니다.

긴 작업 하시느라 고생하셨습니다!🚀

2022-12-18 11:48 UTC, po4tion commented on apps/client/components/Common/Modal/RemoveAlertModal/index.tsx
> +      });
찬혁님이 사용하시는 문법은 tanstack v3 버전입니다. v4버전의 문법은 querykey와 queryFn를 받아 사용하는 것을 default로 하고 있습니다.

2022-12-18 14:49 UTC, po4tion commented on apps/client/components/Recent/History.tsx
> +            onClick={() => push(`/post/${id}`)}
1. map/[id] 로 가보기

2022-12-18 14:54 UTC, po4tion commented on apps/client/components/Recent/History.tsx
> +            `}
거짓말.

2022-12-18 15:12 UTC, po4tion commented on apps/client/contexts/MapProvider/index.tsx
> +          "https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/markerStar.png";
todo

2022-12-18 15:26 UTC, po4tion commented on apps/client/pages/recent/nationality.page.tsx
> +          {tags.map(({ ID, NAME }) => (
이거 복치복치에서 가져온건데 별로인 것 같아요

2022-12-18 15:29 UTC, po4tion commented on apps/client/pages/recent/restaurant.page.tsx
> +      {/* border는 임시로 넣어놨음 */}
옹키
\

2022-12-18 15:40 UTC, po4tion commented on apps/client/recoil/atoms/map.ts
>  // ha: west oa: east pa: south qa: north 순서
![image](https://user-images.githubusercontent.com/55759551/208306918-0f529d81-a481-4698-b89e-9615a55f2557.png)

기하학에서 OA는 원에서 동쪽을 가리키는 방향의 선분 이름을 가지는 데요. 카카오맵 분들이 이 점을 응용하신 것 같습니다.

2022-12-19 02:11 UTC, po4tion commented on apps/client/@types/index.d.ts
> +  };
[fix: Remove duplicated Util type](https://github.com/toppingskorea/toppings-client/pull/35/commits/c9aec01e1e186ab82d861adc6d4f1d0507d534cd)

2022-12-19 02:12 UTC, po4tion commented on apps/client/assets/svgs/map/index.ts
> +export { default as CurrentPlace } from "./currentPlace.svg";
[fix: map icons place center](https://github.com/toppingskorea/toppings-client/pull/35/commits/9edea5eb089a639ed1461ba8dc280bbe13b05dcb)

2022-12-19 02:12 UTC, po4tion commented on apps/client/apis/recent/index.ts
> +export const getRecentHistory = async () => {
[fix: Add postman address copy in api comment](https://github.com/toppingskorea/toppings-client/pull/35/commits/c0c5c272bf3e4582e2690ee7716912981b661c65)

2022-12-19 02:12 UTC, po4tion commented on apps/client/apis/recent/index.ts
> +export const deleteRecentAllHistory = async () => {
[fix: deleteRecentAllHistory -> deleteAllRecentHistory](https://github.com/toppingskorea/toppings-client/pull/35/commits/01eea2e13eddeda4465b74d2de837b68b22a180c)

2022-12-19 02:13 UTC, po4tion commented on apps/client/assets/svgs/recent/index.ts
> +export { default as NotClickedHeart } from "./notClickedHeart.svg";
[fix: Change ClickedHeart -> OrangeHeart, NotClickedHeart -> EmptyHeart](https://github.com/toppingskorea/toppings-client/pull/35/commits/964255bd5520a155610ab373a7ad8dba96198db0)

그게 더 좋아요

2022-12-19 02:13 UTC, po4tion commented on apps/client/components/Map/Button/FilteringButton.tsx
> +        animate="animate"
[fix: Use framerMocker](https://github.com/toppingskorea/toppings-client/pull/35/commits/dcd097d4ab8fe6c526738831a708e0755edeec14)

2022-12-19 02:13 UTC, po4tion commented on apps/client/components/Map/Button/FilteringButton.tsx
> +            {register.country}
api issue

2022-12-19 02:13 UTC, po4tion commented on apps/client/components/Map/Button/FilteringButton.tsx
> +          <Exit onClick={() => console.log("hi")} />
api issue

2022-12-19 02:14 UTC, po4tion commented on apps/client/components/Map/Button/FilteringButton.tsx
> +          z-index: 10;
[fix: Use zIndexs in theme](https://github.com/toppingskorea/toppings-client/pull/35/commits/a50d84194c6481326106c5cb17b6649eb3ad310f)

2022-12-19 02:14 UTC, po4tion commented on apps/client/components/Common/Modal/RemoveAlertModal/index.tsx
> +const RemoveAlertModal = ({ exit }: Props) => {
[fix: Modal expandability increase](https://github.com/toppingskorea/toppings-client/pull/35/commits/262e587a8913573e7b58e1c89b5b868392ff3b47)

2022-12-19 02:15 UTC, po4tion commented on apps/client/mutations/recent/useFetchEatingHabitByFiltering.ts
> +    UseQueryOptions<Awaited<ReturnType<typeof getEatingHabitByFiltering>>>,
[fix: Change UseQueryOptions -> UseMutationOptions](https://github.com/toppingskorea/toppings-client/pull/35/commits/66ef8c332361ee8e697a5194bda5169d7021d411)

2022-12-19 02:15 UTC, po4tion commented on apps/client/pages/recent/eatingHabit.page.tsx
> +import useFetchEatingHabitByFiltering from "~/mutations/recent/useFetchEatingHabitByFiltering";
[fix: Integrate multiple mutation route](https://github.com/toppingskorea/toppings-client/pull/35/commits/c381c23fd004d28412105c35da08334135d5e0ed)

2022-12-19 02:16 UTC, po4tion commented on apps/client/pages/recent/eatingHabit.page.tsx
> +  const { mutate: recentHistoryMutate } = useUploadRecentHistory();
[fix: Integrate mutate naming convention](https://github.com/toppingskorea/toppings-client/pull/35/commits/ece40ca522e50d3e6739d765177a1fcaeaf72deb)

2022-12-19 02:16 UTC, po4tion commented on apps/client/pages/recent/eatingHabit.page.tsx
> +  const theme = useTheme();
[fix: useTheme use distructing](https://github.com/toppingskorea/toppings-client/pull/35/commits/f768ef5a4e7fdef6f7b9da278bed7e80a72156b7)

2022-12-19 02:17 UTC, po4tion commented on apps/client/pages/recent/index.page.tsx
> +          }}
[fix: Refactoring onClick Handler](https://github.com/toppingskorea/toppings-client/pull/35/commits/9243ae2842ed8f6be3b125391601132698984deb)

2022-12-19 02:17 UTC, po4tion commented on apps/client/pages/recent/index.page.tsx
> +      <SSRSafeSuspense fallback={<div>하이</div>}>
[fix: Add skeleton paragraph](https://github.com/toppingskorea/toppings-client/pull/35/commits/3e3325aea1009de4170165c86349d3f1f3fa0237)

2022-12-19 02:18 UTC, po4tion commented on apps/client/pages/recent/eatingHabit.page.tsx
> +  const { mutate } = useFetchEatingHabitByFiltering({
[fix: Integrate mutate naming convention](https://github.com/toppingskorea/toppings-client/pull/35/commits/ece40ca522e50d3e6739d765177a1fcaeaf72deb)

2022-12-19 02:18 UTC, po4tion commented on apps/client/pages/recent/nationality.page.tsx
> +  });
[fix: Integrate mutate naming convention](https://github.com/toppingskorea/toppings-client/pull/35/commits/ece40ca522e50d3e6739d765177a1fcaeaf72deb)

2022-12-19 02:19 UTC, po4tion commented on apps/client/components/Recent/History.tsx
> +          y: 0
[fix: Remove useless padding y=0](https://github.com/toppingskorea/toppings-client/pull/35/commits/1f3e195cfb46184029109b270fe1d7a82cb1587c)

맞아요... 감사합니다!

2022-12-19 02:20 UTC, po4tion commented on apps/client/components/Recent/History.tsx
> +            `}
[fix: Move css props placement](https://github.com/toppingskorea/toppings-client/pull/35/commits/bc467ced6a6e98cb1bdaf2bd9b3bc355c15abf66)

하나만 그래요....우소!

2022-12-19 02:21 UTC, po4tion commented on apps/client/pages/recent/nationality.page.tsx
> +            display: flex;
[fix: Add scorll style](https://github.com/toppingskorea/toppings-client/pull/35/commits/7c0e42260741f37ddad41dd932836a6074c0439f)
[fix: Change bottom roundeTag color](https://github.com/toppingskorea/toppings-client/pull/35/commits/64c4b5dce0991a40270a9340f09601a23c3864e2)

2022-12-19 02:22 UTC, po4tion commented on apps/client/pages/recent/nationality.page.tsx
> +          {tags.map(({ ID, NAME }) => (
[fix: Change Object Key naming convention in array type](https://github.com/toppingskorea/toppings-client/pull/35/commits/b18d2aeb145ec398b0bd6d671d908ba1a3c7e6e4)

변경하였습니다 소문자로!

2022-12-19 02:22 UTC, po4tion commented on apps/client/pages/recent/nationality.page.tsx
> +            overflow-x: auto;
[fix: Add scorll style](https://github.com/toppingskorea/toppings-client/pull/35/commits/7c0e42260741f37ddad41dd932836a6074c0439f)

2022-12-19 02:23 UTC, po4tion commented on apps/client/pages/recent/restaurant.page.tsx
> +      </div>
[fix: Move if has position fixed -> bottom to top](https://github.com/toppingskorea/toppings-client/pull/35/commits/92ff8a9952ca6c1c316bab53d3f60a06ef3c87e6)

2022-12-19 02:24 UTC, po4tion commented on apps/client/pages/recent/restaurant.page.tsx
> +                      weight={weighs.semiBold}
useTheme 썼는데....혹시 어떤 말이죠 이거?

2022-12-19 02:24 UTC, po4tion commented on apps/client/pages/recent/restaurant.page.tsx
> +  });
[fix: Integrate mutate naming convention](https://github.com/toppingskorea/toppings-client/pull/35/commits/ece40ca522e50d3e6739d765177a1fcaeaf72deb)

2022-12-19 02:25 UTC, po4tion commented on apps/client/pages/recent/restaurant.page.tsx
> +  >(null);
[fix: Change useState default value null -> undefined](https://github.com/toppingskorea/toppings-client/pull/35/commits/09ae4240f52cd78541c89907e7ca5b4d7fde03c5)

2022-12-19 02:25 UTC, po4tion commented on apps/client/pages/recent/restaurant.page.tsx
> +                      {item.writer}
[fix: Add write prefix 'by'](https://github.com/toppingskorea/toppings-client/pull/35/commits/a95eede29ae76a134c0de44f575928ce5715f38b)

2022-12-19 02:27 UTC, po4tion commented on apps/client/recoil/atoms/map.ts
>    default: null
<img width="591" alt="image" src="https://user-images.githubusercontent.com/55759551/208335812-655b5164-4659-447b-ac63-af08c6e2ea4d.png">

의도적으로 비워져 있다라는 것을 null을 통해 말하고 싶었습니다. 혹시 여기에 의도가 맞지 않을까요?

2022-12-19 03:34 UTC, ChanhyukPark-Tech commented on apps/client/components/Map/Button/FilteringButton.tsx
> +    <Flex.Center
## FIGMA

![image](https://user-images.githubusercontent.com/69495129/208342343-e3484583-f3e1-4507-8c82-9d02707a84bf.png)


## REAL
<img width="239" alt="image" src="https://user-images.githubusercontent.com/69495129/208342352-76f52ac2-8964-48c1-a109-b66ba717786a.png">


필터터링 버튼이 찌그러져있습니다!

2022-12-19 03:40 UTC, ChanhyukPark-Tech commented on apps/client/recoil/atoms/map.ts
>    default: null
아하 오케이입니당

2022-12-19 03:49 UTC, ChanhyukPark-Tech commented on apps/client/components/Common/Modal/RemoveAlertModal/index.tsx
> +      });
확인해보니 맞네요!

혹시 다른 것들도 같이 고쳐주실수있으신가요?

![image](https://user-images.githubusercontent.com/69495129/208343972-eb4257e5-c696-4e31-b9d6-ea7e6865aaf3.png)

2022-12-19 03:51 UTC, ChanhyukPark-Tech commented on apps/client/components/Common/Modal/AlertModal/index.tsx
> +            cancle
cancel 이 맞는것 같습니다!!

2022-12-19 03:55 UTC, ChanhyukPark-Tech commented on apps/client/components/Common/Modal/AlertModal/index.tsx
> +        border-radius: 49.5px;
32~35번째 줄과 똑같은데

css를 따로 분리해서 여기서 사용하는것은 어떤가요?

맨아래에서 예를들어 
```tsx
const ellipseCss = css`
   ${gutter("horizontal", 122)}
        background-color: ${hexToRgba(colors.secondary.E2, 0.9)};
        padding: 15px 74px;
        border-radius: 49.5px;
`
```

로 맨아래에 선언하구 사용이요!

2022-12-19 03:57 UTC, ChanhyukPark-Tech commented on apps/client/pages/recent/restaurant.page.tsx
> +        </ul>
@po4tion 이거 아직 해결이 안되어있습니다!

또한
패딩 left가 필요합니다!!
<img width="617" alt="image" src="https://user-images.githubusercontent.com/69495129/208344805-f15eb8f3-d583-47b4-828c-9f15a9733fd4.png">

2022-12-19 03:58 UTC, ChanhyukPark-Tech commented on apps/client/pages/recent/restaurant.page.tsx
> +        </ul>
<img width="206" alt="image" src="https://user-images.githubusercontent.com/69495129/208344872-ffe3e2d1-e5e6-4c87-bc2c-b0420db28bd5.png">

주황색은 테두리 없어야합니다!!

2022-12-19 03:59 UTC, ChanhyukPark-Tech commented on apps/client/pages/recent/restaurant.page.tsx
> +        </ul>
![image](https://user-images.githubusercontent.com/69495129/208344929-b784391e-4c81-499c-8e0e-861af545d308.png)

피그망마에서의 gap은 4입니다!

2022-12-19 04:00 UTC, ChanhyukPark-Tech commented on apps/client/pages/recent/nationality.page.tsx
> +      marginBottom: 85,
<img width="631" alt="image" src="https://user-images.githubusercontent.com/69495129/208345071-23ac6fb1-a4d9-4fdb-8b49-25401a6f95e7.png">

marginBottom 조정 필요할 것 같습니다!!😎

2022-12-19 04:02 UTC, ChanhyukPark-Tech commented on apps/client/pages/recent/restaurant.page.tsx
> +            }
scroll hidden이라는 css랑 합치는것은 어떤가요?

2022-12-19 04:10 UTC, po4tion commented on apps/client/components/Common/Modal/RemoveAlertModal/index.tsx
> +      });
[fix: tanstackv3 invalidateQueries -> tanstackv4](https://github.com/toppingskorea/toppings-client/pull/35/commits/b3bc4b5e1876562730c5da7d6e0890e780f113d6)

2022-12-19 04:29 UTC, po4tion commented on apps/client/contexts/MapProvider/index.tsx
> +          "https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/markerStar.png";
이거 로티 파일 사용할 수 있는거 맞나요? 카카오 맵은 지원 안하는 것 같아요

2022-12-19 05:20 UTC, po4tion commented on apps/client/pages/recent/nationality.page.tsx
> +            display: flex;
[fix: Change nationality top navigation gap and bottom roundtag placement](https://github.com/toppingskorea/toppings-client/pull/35/commits/9e2c3f912e0b906ba724c5d1e05a776b1fcfd171)

추가 개선

2022-12-19 05:39 UTC, po4tion commented on apps/client/pages/recent/restaurant.page.tsx
> +                    {item.type}
<img width="129" alt="image" src="https://user-images.githubusercontent.com/55759551/208355349-127ec0a1-9564-47cc-b62c-751975c708db.png">

되어 있는 거 아닌가요?

2022-12-19 05:41 UTC, po4tion commented on apps/client/pages/recent/restaurant.page.tsx
> +                    {item.type}
[fix: Add vertical gutter in restaurant list](https://github.com/toppingskorea/toppings-client/pull/35/commits/566dc85fedbf13ad7a292734dc1d44ba0f534e47)

식당 이름은 있어서 gap만 추가하였습니다!

2022-12-19 05:42 UTC, po4tion commented on apps/client/pages/recent/restaurant.page.tsx
> +                  gap: 7px;
[fix: Remove useless css props](https://github.com/toppingskorea/toppings-client/pull/35/commits/eb61a32a692236c6aabcefa275e39df2f1136f39)

필요가 없었네용 감사합니다!

2022-12-19 05:44 UTC, po4tion commented on apps/client/pages/recent/restaurant.page.tsx
> +            </Flex>
[fix: Use already exist component(heart, text duo)](https://github.com/toppingskorea/toppings-client/pull/35/commits/912d4153e05845e3367f4c0724807564d4f8d5ab)


감사합니다. 야무지네요

2022-12-19 06:17 UTC, po4tion commented on apps/client/pages/recent/restaurant.page.tsx
> +        </ul>
[fix: Add TagFamily](https://github.com/toppingskorea/toppings-client/pull/35/commits/acbbe06bf0e4b2876de5f4b7f7185947e518b5a8)

2022-12-19 06:18 UTC, po4tion commented on apps/client/pages/recent/restaurant.page.tsx
> +        </ul>
[fix: Change TagFamily's gap 20 -> 4](https://github.com/toppingskorea/toppings-client/pull/35/commits/d60782521e8a561dde4a2c5fdbdded98ddcd3f93)

2022-12-19 06:51 UTC, po4tion commented on apps/client/components/Map/Button/FilteringButton.tsx
> +    <Flex.Center
svg issue...

2022-12-20 11:44 UTC, po4tion commented on apps/client/components/Common/Modal/AlertModal/index.tsx
> +            cancle
[fix: 'cancle' word that does not exist](https://github.com/toppingskorea/toppings-client/pull/35/commits/8f7266cd5e42c7ef048889b81687fca90c2cf49c)

감사합니다.. 익스텐션 쓰고도 모르다니 바보네요 ㅠㅠ

2022-12-20 12:09 UTC, po4tion commented on apps/client/components/Common/Modal/AlertModal/index.tsx
> +        border-radius: 49.5px;
[fix: Duplicate styles are converted to common components](https://github.com/toppingskorea/toppings-client/pull/35/commits/164c9c5f7581af905eaf92dbc38e616d75199cb7)

css말고 styled로 사용하였습니다. theme를 사용하려구요

2022-12-20 12:11 UTC, po4tion commented on apps/client/pages/recent/nationality.page.tsx
> +      marginBottom: 85,
<img width="573" alt="image" src="https://user-images.githubusercontent.com/55759551/208664237-94bd1267-c09e-4e3e-ab09-8c712a0aadae.png">

그 이미 적용이 되어 있는데 업데이트를 안하신 것 같습니다!

2022-12-20 12:15 UTC, po4tion commented on apps/client/pages/recent/restaurant.page.tsx
> +            }
[fix: Use hiddenScroll in TagFamily](https://github.com/toppingskorea/toppings-client/pull/35/commits/cfb04d099193bf44c29f4696075347eaa7276beb)

합치기 완료입니다!

2022-12-20 12:16 UTC, po4tion commented on apps/client/components/Map/Button/FilteringButton.tsx
> +    <Flex.Center
일단 내비두고 시연님이 수정해주시면 바꿔끼겠습니다!
얘만 24x24가 아니라 24x20이라 모양이 이상합니다!

2022-12-20 12:31 UTC, po4tion commented
<img width="80" alt="image" src="https://user-images.githubusercontent.com/55759551/208667854-0fb608ba-4bbc-45b1-9013-b59fdc0a5929.png">

글씨체 이슈가 있습니다. 중앙 정렬(vertical)임에 틀림없지만 폰트 자체에 글씨 하단에 여백이 붙어있습니다.

2022-12-20 12:36 UTC, po4tion commented on apps/client/components/Map/Button/FilteringButton.tsx
> +            {register.country}
[fix: Add Category in Map Filterbutton](https://github.com/toppingskorea/toppings-client/pull/35/commits/3a4081820ac15cf282eb60133c94d77245aff8d4)

해결완료입니다!

2022-12-20 12:45 UTC, po4tion commented on apps/client/components/Map/Button/FilteringButton.tsx
> +          <Exit onClick={() => console.log("hi")} />
[fix: Add Filterbutton next to currentSelectCategory's Exit click event](https://github.com/toppingskorea/toppings-client/pull/35/commits/c7bd9202d85110ac6e80e492d96d00a0206c529c)

구현완료!

2022-12-21 14:40 UTC, merged