History event eatinghabit
toppingskorea/toppings-client pull request #42
Opened 2023-01-04 06:26 UTC by po4tion

# Describe your changes
1. 히스토리 클릭 후, 지도로 이동하여 주변 식당 검색 완료
2. eating habit diet or religion 클릭시 지도로 이동하여 주변 식당 검색 완료
3. Map에서 View lists 클릭 시 지도에 보여지고 있는 식당들 Card 형태로 보여주기 완료
4. 지도 1시 방향 검색한 키워드 exit 버튼 기능 추가(+ 필터링 취소 시 맨 처음 지도 위치로 이동)
## Issue ticket number and link (optional)

## Checklist

- [ ] 🤔 이 프로젝트의 스타일 가이드를 따르나요?
- [ ] 🤔 머지하기 전에 스스로 코드에 문제가 없음을 확인했나요?
- [ ] 🤔 필요한 주석을 필요한 곳에 넣어주었나요?
- [ ] ⛔️ (필수) base 브랜치를 pull 받았나요?!

## Next Step Todo (optional)

## Questions

- 💬 질문 사항이에요!
- 🤷‍♂️ 확인 받고 싶은 부분이에요!
- 🔥 이건 꼭 확인해주세요!

2023-01-04 13:44 UTC, ChanhyukPark-Tech commented
1월5일 리뷰하겠습니다!
긴 작업 감사합니다!!

2023-01-05 12:28 UTC, ChanhyukPark-Tech commented
http://localhost:3000/recent/restaurant

에서 엔터누르지 않아도 자동으로 debounce걸어서 검색되게 해주실수있나요?

2023-01-05 12:32 UTC, ChanhyukPark-Tech commented
<img width="591" alt="image" src="https://user-images.githubusercontent.com/69495129/210780842-b39db747-de95-4771-8d16-bf390b356c09.png">

여기서 Low carb클릭하면 API이슈 발생합니다. 띄어쓰기가 있어서 그럽니다.
규남님과 카멜케이스로 진행하기로 약속했습니다.

<img width="578" alt="image" src="https://user-images.githubusercontent.com/69495129/210780979-15179544-fb63-4052-8d33-0b509b471c33.png">


위처럼 진행해해야할것 같습니다!

2023-01-05 12:37 UTC, ChanhyukPark-Tech requested changes
<img width="738" alt="image" src="https://user-images.githubusercontent.com/69495129/210781916-8dad3f77-45db-4d65-902f-6177dff13488.png">


여기서 Angola버튼 클릭시 무반응입니다!

2023-01-05 12:37 UTC, ChanhyukPark-Tech commented on apps/client/@types/restaurant.d.ts
> +    SearchByCountryDTO,
바꾸신 이유를 알 수 있을까요?

Card와 SearchByCountry와는 연관이 없는것 같아서요
저는 BaseDTO에서 확장하여 CardDTO를 만들었었습니다ㅣ!

2023-01-05 12:37 UTC, ChanhyukPark-Tech commented on apps/client/components/Common/RestaurantCard/index.tsx
> +                justify-content: flex-end;
Flex 에 justify라는 props가 있습니다!

2023-01-05 12:39 UTC, ChanhyukPark-Tech reviewed
<img width="701" alt="image" src="https://user-images.githubusercontent.com/69495129/210782175-23bfc1c0-1f44-4fda-8c83-d33d75c55bdf.png">

view list에 식당이 차있는건 어떠한 상황에 확인할 수 있나요?
레스토랑 렌더링 된것 확인하고 싶은데 어떻게 확인해야할지 방법을 모르겠습니다!

2023-01-05 12:42 UTC, ChanhyukPark-Tech commented on apps/client/components/Map/Button/ListButton.tsx
> +const ListButton = ({ isViewList }: Props) => {
이 버튼은 리스트일때 / 맵일때 둘다쓰이는데 
ListButton은 말이 어휘적으로 안맞는것 같습니다!
ViewStatusButton정도는 어떠신가요?!

2023-01-05 12:43 UTC, ChanhyukPark-Tech commented on apps/client/components/Map/Button/ListButton.tsx
> +  isViewList?: true;
isViewList라는 props를 받는다면
이 버튼은 평생 
View map, View List밖에 기능할 수 없습니다.
props가 더 많아지더라도 onClickHandler 와 text를  따로따로 외부에서 주입받는것은 어떤가요?
그러면 같은 UI의 다른 기능버튼을 언제든 만들 수 있으니까요!

2023-01-05 12:43 UTC, ChanhyukPark-Tech commented on apps/client/components/Map/Button/ListButton.tsx
> +      whileHover="whileHover"
hover시에 현재 아무런 반응이없는데 어떠한 기능인가요?!

2023-01-05 12:44 UTC, ChanhyukPark-Tech commented on apps/client/components/Map/Button/ListButton.tsx
> +        padding: 8px 21px;
@toss/emotion-utils에서 제공해주는 padding함수를 이용하는것은 어떠신가요? 
x와, y값을 줄 수 있어서 보다 명시적인것 같아서요!!

2023-01-05 12:44 UTC, ChanhyukPark-Tech commented on apps/client/components/Recent/History/index.tsx
> +  const clickHandler = (
조금더 명확한 함수명을 지어주시는것은 어떤가요?

2023-01-05 12:46 UTC, ChanhyukPark-Tech commented on apps/client/hooks/useCurrentLocation.ts
> +      enableHighAccuracy: true,
이거 성능상 안좋다는 얘기를 들은 것 같은데, 약간의 오차를 주더라도 꺼둘까요?!

2023-01-05 12:48 UTC, ChanhyukPark-Tech requested changes
thx

2023-01-05 12:48 UTC, ChanhyukPark-Tech commented on apps/client/pages/map/index.page.tsx
> +        {currentSelectCategory.length ? <Map.ListButton /> : <div />}
거짓일시 div를 랜더링하는이유가 무엇인가요?

2023-01-05 12:48 UTC, ChanhyukPark-Tech commented on apps/client/pages/map/viewList.page.tsx
> +            height: 27px;
size라는 함수를 이용해주세요! px이라는 suffix를 붙히지 않아도 됩니다!

2023-01-05 12:48 UTC, ChanhyukPark-Tech commented on apps/client/pages/map/viewList.page.tsx
> +            }}
이정도 onClickHandler라면 함수로 분리해주시는것은 어떤가요?😃

2023-01-05 15:02 UTC, po4tion commented on apps/client/pages/map/index.page.tsx
> +        {currentSelectCategory.length ? <Map.ListButton /> : <div />}
currentSelectCategory.length && <Map.ListButton /> 로 할 경우 에러가 발생합니다. 이유는 Map의 children 타입은 JSX.Element[] 집합이라 boolean 값을 가질 수 없기 때문입니다. 이녀석 하나 때문에 타입을 바꾸는 것은 별로라고 생각되어 삼항 연산자로 태그를 리턴하도록 했습니다.

2023-01-05 15:05 UTC, po4tion commented on apps/client/pages/map/viewList.page.tsx
> +            height: 27px;
[fix: width, height 묶음은 size 함수로 리팩토링](https://github.com/toppingskorea/toppings-client/pull/42/commits/7eeffec980ce721bc1e7f1c25550c9ec9871a048)

2023-01-05 23:33 UTC, po4tion commented on apps/client/components/Common/RestaurantCard/index.tsx
> +                justify-content: flex-end;
[fix: Flex의 attr로 있는 justify 사용](https://github.com/toppingskorea/toppings-client/pull/42/commits/eeb1b2ce411937e147ab4e667805966ba65afea3)

수정완료하였습니다 감사합니다!

2023-01-05 23:50 UTC, po4tion commented
> <img alt="image" width="591" src="https://user-images.githubusercontent.com/69495129/210780842-b39db747-de95-4771-8d16-bf390b356c09.png">
> 
> 여기서 Low carb클릭하면 API이슈 발생합니다. 띄어쓰기가 있어서 그럽니다. 규남님과 카멜케이스로 진행하기로 약속했습니다.
> 
> <img alt="image" width="578" src="https://user-images.githubusercontent.com/69495129/210780979-15179544-fb63-4052-8d33-0b509b471c33.png">
> 
> 위처럼 진행해해야할것 같습니다!
> ## 에러화면
> 
> <img alt="image" width="721" src="https://user-images.githubusercontent.com/69495129/210781024-822e88c2-125c-459f-a4e8-e07f776cec63.png">

[fix: content 타입명에 공백이 있을 경우 공백 제거하여 이어붙이기](https://github.com/toppingskorea/toppings-client/pull/42/commits/835f98ae71fa86b20566bf141299ce8e9cd90cd5)

2023-01-06 00:02 UTC, po4tion commented on apps/client/pages/map/viewList.page.tsx
> +            }}
[fix: 고비용의 클릭 핸들러 따로 분리화](https://github.com/toppingskorea/toppings-client/pull/42/commits/4da11c0897d20d5559fa0472298e73cc4b7be494)

찬혁님은 useCallback이나 useMemo를 사용할 때 기준점이 뭔가요?

2023-01-06 00:47 UTC, po4tion commented on apps/client/components/Map/Button/ListButton.tsx
> +const ListButton = ({ isViewList }: Props) => {
[fix: ListButton -> ViewStatusButton list와 map 둘다 보여줘야 하기 때문에 네이밍 변경](https://github.com/toppingskorea/toppings-client/pull/42/commits/f68c7516c0ca004d08a70c539f41e1efaf70842c)

맞네요! 감사합니다. 상황이 2개일 때에 맞춰 네이밍 센스를 발휘했어야 하는데 단순하게 생각했습니다!

2023-01-06 02:17 UTC, po4tion commented on apps/client/components/Map/Button/ListButton.tsx
> +  isViewList?: true;
[fix: ViewStatusButton 확장성 리팩토링](https://github.com/toppingskorea/toppings-client/pull/42/commits/7c0515c5014b8a480b5ce0156c6ce36d2145d3ff)

확장성을 고려하지 못했네요 감사합니다!

2023-01-06 04:00 UTC, po4tion commented on apps/client/hooks/useCurrentLocation.ts
> +      enableHighAccuracy: true,
속도가 느려지는 쪽의 성능 이슈인가요?

2023-01-06 04:02 UTC, po4tion commented on apps/client/components/Map/Button/ListButton.tsx
> +        padding: 8px 21px;
[fix: toss padding util 함수 사용](https://github.com/toppingskorea/toppings-client/pull/42/commits/3ad8bd6e3515af03fbc097911cebe807e9dfad8c)

감사합니다 놓친 부분 수정완료했습니다!

2023-01-06 04:04 UTC, po4tion commented on apps/client/components/Recent/History/index.tsx
> +  const clickHandler = (
[fix: onClick handler naming 변경](https://github.com/toppingskorea/toppings-client/pull/42/commits/331eb4917bc826be0ce43993776fc0989bba83ae)

historyClickHandler라고 지었는데 혹시 추천해주실 함수명이 있으실까요?

2023-01-06 08:05 UTC, po4tion commented
[fix: restaurant 검색 debounce](https://github.com/toppingskorea/toppings-client/pull/42/commits/b9052353b3555ab05eb22685c7f8d1eced151951)

레스토랑 검색시 디바운스 적용 완료하였습니다. 키보드로 타이핑만 해도 검색이 됩니다!

2023-01-06 15:16 UTC, ChanhyukPark-Tech commented on apps/client/components/Map/Button/ListButton.tsx
> +  isViewList?: true;
@po4tion 변경해주셔서 감사합니다! svg도 상황에 따라 바뀌어야할것 같습니다!

![image](https://user-images.githubusercontent.com/69495129/211041132-c9d4015f-7ef3-4997-abb9-fb4cc50cf133.png)

2023-01-06 15:17 UTC, ChanhyukPark-Tech commented on apps/client/components/Recent/History/index.tsx
> +  const clickHandler = (
so good

2023-01-06 15:19 UTC, ChanhyukPark-Tech commented on apps/client/hooks/useCurrentLocation.ts
> +      enableHighAccuracy: true,
네네 더 정확하게 사용자 위치를 파악하는데 시간이 더 걸리는것 같습니다 또한 디바이스 배터리도 많이 사용한다고 합니다!!

2023-01-06 15:20 UTC, ChanhyukPark-Tech commented on apps/client/pages/map/index.page.tsx
> +        {currentSelectCategory.length ? <Map.ListButton /> : <div />}
그렇군요
근데 심지어
```tsx
currentSelectCategory.length && <Map.ListButton />
```

이렇게 되었을때 currentSelectCategory.length 값이 0 이라면 0 이라는 수가 렌더링되버리는거아닌가요?

2023-01-06 15:21 UTC, ChanhyukPark-Tech commented on apps/client/pages/map/viewList.page.tsx
> +            }}
한 함수나 값을 계산하는 로직이 고비용 이라고 생각하면.. 최적화하는것 같습니다.
하지만 최적화하는 그 자체도 역시  연산이므로 
for 루프가 2번이상 돌경우? 는 무조건해주는편입니다.

2023-01-06 15:22 UTC, ChanhyukPark-Tech commented on apps/client/pages/recent/eatingHabit.page.tsx
> +          const removeSpaceContent = content.replaceAll(" ", "");
충분히 Utils함수로 추상화할 수 있지 않을까요?

replaceSpace 라는 함수를 만든뒤, 
공백이 제거된 값을 반환받는방법이요 
```tsx
replaceAll(" ", "");
```

를 추상화시켜서 숨겨버리는거죠!

2023-01-06 15:40 UTC, ChanhyukPark-Tech commented on apps/client/pages/recent/restaurant.page.tsx
> +            if (!e.target.value.length) setRestaurantList(undefined);
또한 length가 0 일때 return시켜서 fetchRestaurantNameByFilteringMutateDebounce 를 호출 안하게 하는방법도 필요하지 않을까요>!?!

2023-01-09 11:33 UTC, po4tion commented on apps/client/hooks/useCurrentLocation.ts
> +      enableHighAccuracy: true,
highAccuracy 값은 false 처리하겠습니다!

2023-01-09 11:33 UTC, po4tion commented on apps/client/components/Map/Button/ListButton.tsx
> +  isViewList?: true;
[fix: ViewStatusButton 아이콘 추가](https://github.com/toppingskorea/toppings-client/pull/42/commits/e041fb1d0eb82b7f70557cd4a1f87675fefa20bd)

수정 완료하였습니다!

2023-01-09 11:35 UTC, po4tion commented on apps/client/hooks/useCurrentLocation.ts
> +      enableHighAccuracy: true,
[fix: watchPosition highAccuracy 성능 이슈로 제거](https://github.com/toppingskorea/toppings-client/pull/42/commits/81f7c653de0aa5f3d9db8a00623ed43356d55e6f)

수정 완료하였습니다!

2023-01-09 11:38 UTC, po4tion commented on apps/client/pages/map/index.page.tsx
> +        {currentSelectCategory.length ? <Map.ListButton /> : <div />}
맞습니다! 첫번째 연산으로 false가 되면 해당 길이 0이 반영됩니다

2023-01-09 11:38 UTC, po4tion commented on apps/client/pages/map/viewList.page.tsx
> +            }}
좋은 의견 감사합니다!

2023-01-09 11:42 UTC, po4tion commented on apps/client/pages/recent/eatingHabit.page.tsx
> +          const removeSpaceContent = content.replaceAll(" ", "");
[fix: replaceSpace 유틸함수 생성](https://github.com/toppingskorea/toppings-client/pull/42/commits/549a65fc9692ec8d2516a1b586f8fa8eaf88c07a)

좋은 의견입니다!

2023-01-09 11:48 UTC, po4tion commented on apps/client/pages/recent/restaurant.page.tsx
> +            if (!e.target.value.length) setRestaurantList(undefined);
[fix: restaurant 검색 debounce 수정사항 적용, length가 0일 경우 검색된 데이터들 삭제](https://github.com/toppingskorea/toppings-client/pull/42/commits/ece939424ba316d5bf36cac8d323ab8837150908)

위의 리뷰도 포함되어 있습니다!

2023-01-09 11:52 UTC, merged

2023-01-09 11:52 UTC, ChanhyukPark-Tech commented
@po4tion thx for hard works