History event nationality
toppingskorea/toppings-client pull request #43
Opened 2023-01-09 14:20 UTC by po4tion

# Describe your changes

- 히스토리 클릭 후, 지도로 이동하여 주변 식당 검색 완료
- history에서 country 클릭시 지도로 이동하여 주변 식당 검색 완료
- viewList page Topic recoil 생성
- refactorings(hook이 너무 많은 컴포넌트들 hooks.ts 파일로 이전)

## Issue ticket number and link (optional)

## Checklist

- [X] 🤔 이 프로젝트의 스타일 가이드를 따르나요?
- [X] 🤔 머지하기 전에 스스로 코드에 문제가 없음을 확인했나요?
- [X] 🤔 필요한 주석을 필요한 곳에 넣어주었나요?
- [X] ⛔️ (필수) base 브랜치를 pull 받았나요?!

## Next Step Todo (optional)

## Questions

- 💬 질문 사항이에요!
- 🤷‍♂️ 확인 받고 싶은 부분이에요!
- 🔥 이건 꼭 확인해주세요!

2023-01-10 13:41 UTC, ChanhyukPark-Tech requested changes
thx for your hardworks

2023-01-10 13:41 UTC, ChanhyukPark-Tech commented on apps/client/components/Recent/History/History.hooks.ts
> +  };
switch문으로
category가 Name일때 ~ Habit일때~ 
이런식으로 처리하는게 가독성에 좋을 것 같은데 어떠신가요?

2023-01-11 01:21 UTC, ChanhyukPark-Tech commented on apps/client/components/Recent/History/History.hooks.ts
> +  const { data: recentHistories } = useFetchRecentHistory();
history들을 불러오는것이니 
```suggestion
  const { data: recentHistories } = useFetchRecentHistories();
```

라고 명명하는것은 어떠신가요?!

2023-01-11 13:26 UTC, po4tion commented on apps/client/components/Recent/History/History.hooks.ts
> +  };
[fix: 조건이 3개인 경우 if문 중첩 -> case문 변경](https://github.com/toppingskorea/toppings-client/pull/43/commits/54cd4a914507e96adb77115d32cc9633dc6bff8a)

수정하였습니다. 근데 53번째 줄과 69,70번째줄은 중복 로직인데 switch문을 사용할 경우에는 처리할 방법이 없나요?

2023-01-11 13:29 UTC, po4tion commented on apps/client/components/Recent/History/History.hooks.ts
> +  const { data: recentHistories } = useFetchRecentHistory();
[ix: history들을 fetch해올 때 여러 history들을 가져오므로 histories로 변경](https://github.com/toppingskorea/toppings-client/pull/43/commits/92c6ba13e009d8f481a4461e0ebd80015cd6cbc7)

감사합니다. 수정완료하였습니다!

2023-01-11 13:44 UTC, merged