Feat qa map
toppingskorea/toppings-client pull request #65
Opened 2023-01-24 16:03 UTC by po4tion

# Describe your changes

- [x]  History page에서 nationality, Eating habit, restaurat 눌러서 이동된 후에 뒤로가기 버튼을 누르면 이전 행동이 아닌 history page로 이동하게 변경
- [x]  histories default로 10개까지만 보여주고 more recent 버튼 클릭시 이전 10개 데이터 가져와서 보여주기
- [x]  remove all UI. Figma와 통일하기
- [x]  음식점 검색, 국적 검색 시 검색 바 placeholder를 Search restaurant, Search nationality로 변경하기
- [x]  필터가 없을 경우 view list의 주황색 뱃지 제거하기
- [x]  View lists → View list 텍스트 변경
- [x]  지도 default distance 6, max distance 13

## Test method (상대방이 이 PR을 테스트할 수 있는 방법을 설명해주세요!)

http://localhost:3000/recent 들어가셔서 확인해보시면 됩니다!

## Checklist

- [ ] 🤔 이 프로젝트의 스타일 가이드를 따르나요?
- [ ] 🤔 머지하기 전에 스스로 코드에 문제가 없음을 확인했나요?
- [ ] 🤔 필요한 주석을 필요한 곳에 넣어주었나요?
- [ ] ⛔️ (필수) base 브랜치를 pull 받았나요?!

## Next Step Todo (optional)

## Questions

- 💬 질문 사항이에요!
- 🤷‍♂️ 확인 받고 싶은 부분이에요!
- 🔥 이건 꼭 확인해주세요!

2023-01-24 16:35 UTC, ChanhyukPark-Tech requested changes
thx for your hardworks!! thank you 😊

2023-01-24 16:35 UTC, ChanhyukPark-Tech commented on apps/client/components/Kakao/Buttons/ViewStatusButton.tsx
> +        left: 50%;
아니군요, string도 잘 들어갑니다.

```tsx
 ${position("fixed", {
          bottom: dimensions.bottomNavigationHeight + 16,
          left: "50%"
        })}
```

2023-01-24 16:35 UTC, ChanhyukPark-Tech commented on apps/client/components/Layout/TopNavigator/index.tsx
> +    }
cool

2023-01-24 16:35 UTC, ChanhyukPark-Tech commented on apps/client/components/Recent/History/index.tsx
> +        ${hiddenScroll}
![image](https://user-images.githubusercontent.com/69495129/214351849-fba097ce-4403-46ab-9ce7-3285f20727e1.png)

아래부분 background-color white필요할 것 같습니다!

2023-01-24 16:35 UTC, ChanhyukPark-Tech commented on apps/client/pages/map/viewList.page.tsx
>    return (
viewList page가 이상해졌습니다. 확인 부탁드립니다. 2가지 경우 모두 이상합니다. (퍼블리싱)


# 데이터가 있는 경우
![image](https://user-images.githubusercontent.com/69495129/214352126-a65d7141-b99c-4eb5-8437-31eaac09e463.png)

# 데이터가 없는경우(엠티뷰 렌더링 필요)
![image](https://user-images.githubusercontent.com/69495129/214352271-709517d3-8cb2-46d9-bf93-a35fe5eb9b19.png)

2023-01-24 16:35 UTC, ChanhyukPark-Tech commented on apps/client/pages/map/viewList.page.tsx
>    return (
필터링이 있는경우는 뱃지를 살려두는것으로 알고있습니다!
전체 검색인 경우만 뱃지 삭제하고요!

2023-01-27 02:02 UTC, k-gn reviewed
LGTM!

2023-01-27 02:02 UTC, k-gn commented on apps/admin/components/Reviews/ReviewDetail/index.tsx
> +  const [rejectCause, setRejectCause] = useState("");
Good

2023-01-27 03:00 UTC, po4tion commented on apps/client/constants/Motions.ts
> +    translateX: "-50%"
[fix: translateX를 ViewStatusButton에서 내부 스타일로 적용합니다.](https://github.com/toppingskorea/toppings-client/pull/65/commits/3986b736718e812d171b86a4bb1971478f95a425)

너무 좋은 말입니다! 감사합니다!

2023-01-27 03:02 UTC, po4tion commented on apps/client/components/Kakao/Buttons/ViewStatusButton.tsx
> +        left: 50%;
[fix: left 속성을 position 함수에 넣어줍니다.](https://github.com/toppingskorea/toppings-client/pull/65/commits/d646a1d4f51045c08c9495da511269e3f9423776)

수정 완료하였습니다! 50%가 들어가는 줄 확인을 제대로 못했네용 ㅠㅠ

2023-01-27 03:03 UTC, po4tion commented on apps/client/components/Kakao/Buttons/ViewStatusButton.tsx
>            x: 21,
[fix: ViewStatusButton dim color는 hextorgba function을 사용합니다.](https://github.com/toppingskorea/toppings-client/pull/65/commits/8273415f5cc8a21ec59f0f464b293170f429fd34)

넵 감사합니다!!

2023-01-27 03:42 UTC, po4tion commented on apps/client/components/Kakao/Buttons/ViewStatusButton.tsx
>  const ViewStatusButton = ({ text, onClick, Icon }: Props) => {
[fix: View Status Button Title Text color 수정](https://github.com/toppingskorea/toppings-client/pull/65/commits/8d120801318544a5eff846979dad402087aa3ae2)

감사합니다 수정하였습니다!

2023-01-27 03:49 UTC, po4tion commented on apps/client/components/Recent/History/index.tsx
> +        <MotionButton onClick={() => app.recentHistoriesFetchNextPage()}>
[fix: onClick 이벤트에서 VoidFunction을 주입하기 위해 hisotry hooks에서 handler를 만듭니다.](https://github.com/toppingskorea/toppings-client/pull/65/commits/c13f38bca565f7f409c497703d39ec893095e7f4)

감사합니다 좋은 방법입니다!

2023-01-27 05:39 UTC, po4tion commented on apps/client/components/Layout/TopNavigator/index.tsx
> +    }
[fix: TopNavigator 조건문을 통과하여 존재하는 값은 optional chaining이 필요 없습니다.](https://github.com/toppingskorea/toppings-client/pull/65/commits/89159ad681589a52d8054551469d9e63ff1e792e)

감사합니다 수정하였습니다!

2023-01-27 05:58 UTC, po4tion commented on apps/client/pages/map/viewList.page.tsx
>    return (
1. 데이터가 있는 경우 : [fix: ViewList Page merge 과정에서 사라진 Badge 복구 및 UI 변경](https://github.com/toppingskorea/toppings-client/pull/65/commits/d8e091f99a3f0fd1556df146a6aeae5f026c2379)

2023-01-27 08:00 UTC, ChanhyukPark-Tech commented on apps/admin/components/Reviews/ReviewDetail/index.tsx
> +  const [rejectCause, setRejectCause] = useState("");
이거 내가올린 커밋의 코드인데 환장하네요

2023-01-27 08:03 UTC, merged